### ISSUE TITLE
List buttons and Some Dark Theme Issue

### ISSUE THREAD

**Issue by bakinazik** [elementsinteractive/Noteup#31]
https://user-images.githubusercontent.com/64368231/201494992-d6cde877-fa6f-4c24-aae9-d5337c95e589.mp4

https://user-images.githubusercontent.com/64368231/201494995-9779cc7a-ecce-4aeb-8e78-97a730cd8a82.mp4

**Comment by GarliqBread** [comment]
Fixed on #32
